language: ruby
sudo: true
cache: bundler
bundler_args: "--without development"
before_install: rm Gemfile.lock || true
script:
- bundle exec rake $CHECK
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.2.5
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 4.0" CHECK=rubocop
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 4.0" CHECK=test DEPLOY_TO_FORGE=yes
  - rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="debian-8"
    bundler_args: 
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="ubuntu-1204"
    bundler_args: 
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="ubuntu-1404"
    bundler_args: 
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="ubuntu-1604"
    bundler_args: 
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="centos-7"
    bundler_args: 
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
notifications:
  email: true
deploy:
  provider: puppetforge
  user: onpuppet
  password:
    secure: PMkXVmCANCXgg8wXEPHSoY5G4lcSg6UUlK8N4Ky3O0+/PL8Alix9epmzjSXZTSUV2JSHDUXXuffnD8wcZWow7wnYfi0PvtciPQuOzfSYVaSLcUa9Qt7fFkFr+chnnike10vLn5h5fJZiC+6tSf6QzzpaB4zNiJeZQCk2oxcCnCrpG2UIhMOTsENDgV88UieFzwsTk0RqyMRy88ORSehz25XNjkvBJNsOUOqDcnXkVsqH4xecTW6g9ALaXKMYzDrlfGSOR3T0NP4BR6NHW2dREHUm6P7nJfdR3h46WxKuEUNwU5h2O0Lw7l6Gvz8aRG4elbOQuhkt8ir10W3KvNXhWorxdgHONP3ucyzzZ3/uXqpDbE60LU3BaXqL10HBofKQGqUnsyH5Vhj4lxMXzc05ur1o6sDHd5ucklYVpBg50/iOPffq+CXnyDBBG0sHCov66zhbxXhA90ZFvrgiEpUmp5K0HGOEON5LvzwgK41G4rar4SoYvztdHm6iqQDJGgdlMvl/UPF0kBkMBxtgPRZc5CUjUOsYHDHzhwMAIhogLvXGIWcxkQgwLfCc7gg/gWKlJYCijzURkcoH5D0gY2iP83HsU9gh8NyVQYG5U5qVSK1pWnX1aL4heNeLVEcpUNTZus6T5ktukR4QOQflDH1lHsWIFNfkTMY1oMoDPf8cCnQ=
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
